=== andreiolaru-ro/FLASH-MAS/src-schema/deployment-schema.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Copyright (C) 2013 Andrei Olaru, Marius-Tudor Benea, Nguyen Thi Thuy 
	Nga, Amal El Fallah Seghrouchni, Cedric Herpson. This file is part of tATAmI-PC. 
	tATAmI-PC is free software: you can redistribute it and/or modify it under 
	the terms of the GNU Lesser General Public License as published by the Free 
	Software Foundation, either version 3 of the License, or any later version. 
	tATAmI-PC is distributed in the hope that it will be useful, but WITHOUT 
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
	FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more 
	details. You should have received a copy of the GNU Lesser General Public 
	License along with tATAmI-PC. If not, see <http://www.gnu.org/licenses/>. -->
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://flash.xqhs.net/deployment-schema"
	xmlns:tns="http://flash.xqhs.net/deployment-schema" elementFormDefault="qualified">
	<element name="scenario">
		<complexType>
			<sequence>
				<element name="config" maxOccurs="1" minOccurs="0">
					<complexType>
						<sequence>
							<element name="parameter" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<attribute name="name" type="string" use="required" />
									<attribute name="value" type="string" use="required" />
								</complexType>
							</element>
						</sequence>
						<attribute name="center" type="string" use="optional" />
						<attribute name="here" type="string" use="optional" />
					</complexType>
				</element>
				<element name="support" maxOccurs="unbounded" minOccurs="0">
					<complexType>
						<sequence>
							<element name="parameter" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<attribute name="name" type="string" use="required" />
									<attribute name="value" type="string" use="required" />
								</complexType>
							</element>
						</sequence>
						<attribute name="kind" type="string" use="required" />
						<attribute name="id" type="string" use="optional" />
					</complexType>
				</element>
				<element name="loader" maxOccurs="unbounded" minOccurs="0">
					<complexType>
						<sequence>
							<element name="parameter" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<attribute name="name" type="string" use="required" />
									<attribute name="value" type="string" use="required" />
								</complexType>
							</element>
						</sequence>
						<attribute name="for" type="string" use="required" />
						<attribute name="classpath" type="string" use="required" />
					</complexType>
				</element>
				<element name="package" type="string" minOccurs="0"
					maxOccurs="unbounded" />
				<element name="agent" maxOccurs="unbounded" minOccurs="0">
					<complexType>
						<sequence>
							<element name="component" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="parameter" minOccurs="0" maxOccurs="unbounded">
											<complexType>
												<attribute name="name" type="string" use="required" />
												<attribute name="value" type="string" use="required" />
											</complexType>
										</element>
									</sequence>
									<attribute name="name" type="string" use="required" />
									<attribute name="classpath" type="string" use="optional" />
								</complexType>
							</element>
							<element name="parameter" minOccurs="0" maxOccurs="unbounded">
								<complexType>
									<attribute name="name" type="string" use="required" />
									<attribute name="value" type="string" use="required" />
								</complexType>
							</element>
						</sequence>
						<attribute name="name" type="string" use="optional" />
					</complexType>
				</element>
				<element name="timeline" maxOccurs="1" minOccurs="0">
					<complexType>
						<sequence>
							<element name="event" minOccurs="1" maxOccurs="unbounded">
								<complexType>
									<sequence>
										<element name="message" maxOccurs="unbounded"
											minOccurs="0">
											<complexType>
												<sequence>
													<element name="to" type="string" minOccurs="1"
														maxOccurs="unbounded" />
													<element name="content" type="string" minOccurs="0"
														maxOccurs="1" />
												</sequence>
											</complexType>
										</element>
									</sequence>
									<attribute name="time" type="positiveInteger" use="required" />
								</complexType>
							</element>
						</sequence>
						<attribute name="duration" type="positiveInteger" use="optional">
						</attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== andreiolaru-ro/FLASH-MAS/old-deployment/ChatAgents/deployment-chatAgents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
	Copyright (C) 2021 Andrei Olaru.

	This file is part of Flash-MAS. The CONTRIBUTORS.md file lists people who have been previously involved 
	with this project.

	Flash-MAS is free software: you can redistribute it and/or modify it under the terms of the GNU General 
	Public License as published by the Free Software Foundation, either version 3 of the License, or any 
	later version.

	Flash-MAS is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even 
	the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public 
	License for more details.

	You should have received a copy of the GNU General Public License along with Flash-MAS. If not, see 
	<http://www.gnu.org/licenses/>.
-->

<scenario xmlns="http://flash.xqhs.net/deployment-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://flash.xqhs.net/deployment-schema ../../src-schema/deployment-schema.xsd">

	<config here="127.0.0.1:9002">
		<parameter name="node" value="Central" />
	</config>

	<support kind="websocket" />

	<package>ChatAgents</package>

	<agent name="AgentA">
		<parameter name="loader" value="composite" />
		<parameter name="name" value="agentA" />

		<component name="parametric" />
		<component name="visualizable">
			<parameter name="GUI" value="ChatAgentGui" />
		</component>
		<component name="messaging" />
		<component name="cognitive" />
		<component name="s_claim">
			<parameter name="class" value="ChatAgent" />
			<parameter name="java-code" value="ChatFunctions" />
			<parameter name="otherAgent" value="agentB" />
		</component>
	</agent>
	<agent>
		<parameter name="loader" value="composite" />
		<parameter name="name" value="agentB" />

		<component name="parametric" />
		<component name="visualizable">
			<parameter name="GUI" value="ChatAgentGui" />
		</component>
		<component name="messaging" />
		<component name="cognitive" />
		<component name="s_claim">
			<parameter name="class" value="ChatAgent" />
			<parameter name="java-code" value="ChatFunctions" />
			<parameter name="otherAgent" value="agentA" />
		</component>
	</agent>
</scenario>

=== andreiolaru-ro/FLASH-MAS/src-scenario/ChatAgents/deployment-chatAgents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (C) 2013 Andrei Olaru, Marius-Tudor Benea, Nguyen Thi Thuy Nga, Amal El Fallah Seghrouchni, Cedric Herpson.
  
  This file is part of tATAmI-PC.
  
  tATAmI-PC is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or any later version.
  
  tATAmI-PC is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for more details.
  
  You should have received a copy of the GNU Lesser General Public License along with tATAmI-PC.  If not, see <http://www.gnu.org/licenses/>.
-->
<scen:scenario xmlns:scen="http://flash.xqhs.net/deployment-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://flash.xqhs.net/deployment-schema ../../src-schema/deployment-schema.xsd">

	<scen:config mainHost="server client" mainPort="9002"
		localHost="127.0.0.1" localPort="9002" />
	
    <scen:platform>
		<scen:parameter name="name" value="websocket" />
	</scen:platform>
	   
	<scen:agentPackage>ChatAgents</scen:agentPackage>

	<scen:initial>
		<scen:container name="container-A">
		    <scen:agent>
				<scen:component name="parametric" />
				<scen:component name="visualizable">
					<scen:parameter name="GUI" value="ChatAgentGui" />
			    </scen:component>
				<scen:component name="messaging" />
				<scen:component name="cognitive" />
				<scen:component name="s_claim">
					<scen:parameter name="class" value="ChatAgent" />
					<scen:parameter name="java-code" value="ChatFunctions" />
					<scen:parameter name="otherAgent" value="agentB" />
				</scen:component>

				<scen:parameter name="loader" value="composite" /> 
				<scen:parameter name="name" value="agentA" />
			</scen:agent>
		</scen:container>
		<scen:container name="AliceContainer"><!--  create="false" -->
		    <scen:agent>
				<scen:component name="parametric" />
				<scen:component name="visualizable">
					<scen:parameter name="GUI" value="ChatAgentGui" />
			    </scen:component>
				<scen:component name="messaging" />
				<scen:component name="cognitive" />
				<scen:component name="s_claim">
					<scen:parameter name="class" value="ChatAgent" />
					<scen:parameter name="java-code" value="ChatFunctions" />
					<scen:parameter name="otherAgent" value="agentA" />
				</scen:component>

				<scen:parameter name="loader" value="composite" /> 
				<scen:parameter name="name" value="agentB" />
		    </scen:agent>
		</scen:container>
	</scen:initial>
</scen:scenario>

=== andreiolaru-ro/FLASH-MAS/src-deployment/ChatAgents/deployment-chatAgents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright (C) 2013 Andrei Olaru, Marius-Tudor Benea, Nguyen Thi Thuy 
	Nga, Amal El Fallah Seghrouchni, Cedric Herpson. This file is part of tATAmI-PC. 
	tATAmI-PC is free software: you can redistribute it and/or modify it under 
	the terms of the GNU Lesser General Public License as published by the Free 
	Software Foundation, either version 3 of the License, or any later version. 
	tATAmI-PC is distributed in the hope that it will be useful, but WITHOUT 
	ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS 
	FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more 
	details. You should have received a copy of the GNU Lesser General Public 
	License along with tATAmI-PC. If not, see <http://www.gnu.org/licenses/>. -->
<scenario xmlns="http://flash.xqhs.net/deployment-schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://flash.xqhs.net/deployment-schema ../../src-schema/deployment-schema.xsd">

	<config here="127.0.0.1:9002">
		<parameter name="node" value="Central" />
	</config>

	<support name="websocket" />

	<package>ChatAgents</package>

	<agent name="AgentA">
		<component name="parametric" />
		<component name="visualizable">
			<parameter name="GUI" value="ChatAgentGui" />
		</component>
		<component name="messaging" />
		<component name="cognitive" />
		<component name="s_claim">
			<parameter name="class" value="ChatAgent" />
			<parameter name="java-code" value="ChatFunctions" />
			<parameter name="otherAgent" value="agentB" />
		</component>

		<parameter name="loader" value="composite" />
		<parameter name="name" value="agentA" />
	</agent>
	<agent>
		<component name="parametric" />
		<component name="visualizable">
			<parameter name="GUI" value="ChatAgentGui" />
		</component>
		<component name="messaging" />
		<component name="cognitive" />
		<component name="s_claim">
			<parameter name="class" value="ChatAgent" />
			<parameter name="java-code" value="ChatFunctions" />
			<parameter name="otherAgent" value="agentA" />
		</component>

		<parameter name="loader" value="composite" />
		<parameter name="name" value="agentB" />
	</agent>
</scenario>
